### ISSUE TITLE
1.20 support

### ISSUE THREAD

**Issue by Bayanicool** [CorneliusMa/SilkSpawners_v2#43]
1.20 support is not working

**Comment by Lagggpixel** [comment]
Do you have some more details, i.e. error trace logs or specifics on which parts aren't working?

**Comment by Bayanicool** [comment]
Yes, console says 

"
- [Mon 22:29:58 ERROR Minecraft] null
org.bukkit.command.CommandException: Cannot execute command 'silkspawners' in plugin SilkSpawners_v2 v2.2.0 - plugin is disabled.
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
    at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:929)
    at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
    at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
    at net.minecraft.commands.Commands.performCommand(Commands.java:324)
    at net.minecraft.commands.Commands.performCommand(Commands.java:308)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2295)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2255)
    at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    at net.minecraft.server.TickTask.run(TickTask.java:18)
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318)
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311)
    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:128
    "
    
    THIS IS DUE TO THE PLUGIN DISABLING BECAUSE 1.20 "IS NOT SUPPORTED"

**Comment by Lagggpixel** [comment]
1.20 is currently unsupported by the main branch on github and the jar file in spigot. I have opened a pull request and have also uploaded a version of the jar file in my own fork(it is public if you want to fetch it).

**Comment by Lagggpixel** [comment]
You do realise I'm not the plugin owner, I've just maintained it to be supporting 1.20.
