### ISSUE TITLE
SilkSpawners version 2.3.0 doesn't work with PaperSpigot 1.20.4 Build#497

### ISSUE THREAD

**Issue by wpmidia** [CorneliusMa/SilkSpawners_v2#55]
**Plugin page says that it works up to version 1.21, but why it doesn't work on my server 1.20.4?**

`[09:19:10 ERROR]: Error occurred while enabling SilkSpawners_v2 v2.3.0 (Is it up to date?)
java.lang.RuntimeException: java.lang.ClassNotFoundException: de.corneliusmay.silkspawners.nms.1_13_R2.NMSHandler
        at de.corneliusmay.silkspawners.plugin.version.MinecraftVersionChecker.load(MinecraftVersionChecker.java:33) ~[SilkSpawners_v2.3.0.jar:?]
        at de.corneliusmay.silkspawners.plugin.SilkSpawners.onEnable(SilkSpawners.java:56) ~[SilkSpawners_v2.3.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: de.corneliusmay.silkspawners.nms.1_13_R2.NMSHandler
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:421) ~[?:?]
        at java.lang.Class.forName(Class.java:412) ~[?:?]
        at de.corneliusmay.silkspawners.plugin.version.MinecraftVersionChecker.load(MinecraftVersionChecker.java:30) ~[SilkSpawners_v2.3.0.jar:?]`

**Comment by rxchard** [comment]
Thanks, will be fixed in a second

**Comment by rxchard** [comment]
Fixed. Simply redownload the current release.
